[package]
name = "bound_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.winit_event_helper]
path = "C:/Users/gebruiker/IdeaProjects/winit_event_helper"
features = ["save_device_inputs"]

[dependencies]
vulkano = "0.32.3"
vulkano-shaders = "0.32.0"
vulkano-win = "0.32.0"
bytemuck = "1.12.3"
winit = "0.27.5"
glam = "0.22.0"
fps_counter = "2.0.0"
image = "0.24.5"
