[package]
name = "bound_engine"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.32.3"
vulkano-shaders = "0.32.0"
vulkano-win = "0.32.0"
bytemuck = "1.13.0"
winit = "0.27.5"
winit-fullscreen = "1.0.0"
winit_event_helper = "0.4.2"
glam = "0.23.0"
fps_counter = "2.0.0"
image = "0.24.5"
itertools = "0.10.5"
petgraph = "0.6.3"
vec_cycle = "0.1.0"
rand_distr = "0.4.3"
rand = "0.8.5"